---
- hosts: nokia_classic
  vars:
    - ansible_network_os: nokia.sros.classic
  vars_prompt:
    - name: ansible_user
      prompt: "Username"
      private: no
    - name: ansible_password
      prompt: "Password"
  connection: network_cli
  gather_facts: No

  collections:
  - nokia.sros

  tasks:
  - name: backup
    cli_config:
      backup: yes
      backup_options:
        dir_path: /tmp
    register: backup_info

  - name: backup details
    debug:
      msg: "{{backup_info}}"

  - name: do some config
    cli_config:
      config: |
        configure service
          customer 100 name nobody create
            back
          vpls 100 name midnight customer 100 create
            exit all

  - name: "restore backup (Error: Classic-CLI does not support restore)"
    cli_config:
      replace: 'true'
      config: "{{ lookup('file', backup_info.backup_path) }}"

...
